# Generated by Django 5.2.3 on 2025-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_qualifications_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this teacher has been approved by an admin.', verbose_name='Approved'),
        ),
        migrations.DeleteModel(
            name='TeacherRequest',
        ),
    ]
