# Generated by Django 5.2.3 on 2025-06-23 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_teacher_qualifications_teacher_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether the record is marked as deleted.', verbose_name='Is deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created the record.', null=True, verbose_name='IP address')),
                ('author', models.EmailField(blank=True, help_text='Email of the user who created the record.', max_length=254, null=True, verbose_name='Author')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata stored as JSON.', null=True, verbose_name='Metadata')),
                ('qualifications', models.TextField(help_text='Qualifications provided for the teacher request.', verbose_name='Qualifications')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', help_text='Current status of the teacher request.', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Date and time when the request was reviewed.', null=True, verbose_name='Reviewed at')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('user', models.ForeignKey(help_text='User requesting to become a teacher.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher Request',
                'verbose_name_plural': 'Teacher Requests',
            },
        ),
    ]
