# Generated by Django 5.2.3 on 2025-06-25 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_teacher_qualifications_teacher_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image of the teacher (optional).', null=True, upload_to='teacher_profiles/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_expertise',
            field=models.CharField(blank=True, help_text='Subjects the teacher is qualified to teach.', max_length=255, null=True, verbose_name='Subject Expertise'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(help_text='User associated with the teacher profile.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
    ]
