# Generated by Django 5.2.3 on 2025-06-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_teacher_bio_teacher_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, help_text="Teacher's biography or description.", null=True, verbose_name='Bio'),
        ),
    ]
