# Generated by Django 5.2.3 on 2025-06-21 19:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the course (0.00 for free).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether the record is marked as deleted.', verbose_name='Is deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created the record.', null=True, verbose_name='IP address')),
                ('author', models.EmailField(blank=True, help_text='Email of the user who created the record.', max_length=254, null=True, verbose_name='Author')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata stored as JSON.', null=True, verbose_name='Metadata')),
                ('course', models.ForeignKey(help_text='Course the user is enrolled in.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.course', verbose_name='Course')),
                ('user', models.ForeignKey(help_text='User enrolled in the course.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether the record is marked as deleted.', verbose_name='Is deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created the record.', null=True, verbose_name='IP address')),
                ('author', models.EmailField(blank=True, help_text='Email of the user who created the record.', max_length=254, null=True, verbose_name='Author')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata stored as JSON.', null=True, verbose_name='Metadata')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(help_text='Review comment.', verbose_name='Comment')),
                ('course', models.ForeignKey(help_text='Course being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='course.course', verbose_name='Course')),
                ('user', models.ForeignKey(help_text='User who submitted the review.', on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
