# Generated by Django 5.2.3 on 2025-06-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_price_courseenrollment_coursereview'),
        ('users', '0002_remove_profile_qualifications_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher who created the course.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.teacher', verbose_name='Teacher'),
        ),
    ]
