# Generated by Django 5.2.3 on 2025-06-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_teacherapplication_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapplication',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City of residence.', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='identity_card',
            field=models.CharField(blank=True, default='', help_text='National identity card number.', max_length=100, verbose_name='Identity Card Number'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current status of the application.', max_length=20, verbose_name='Status'),
        ),
    ]
