# Generated by Django 5.2.3 on 2025-06-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_teacherapplication_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='identity_card_picture',
            field=models.ImageField(blank=True, help_text='Upload a clear image of your identity card.', null=True, upload_to='identity_cards/', verbose_name='Identity Card Picture'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='city',
            field=models.CharField(help_text='City of residence.', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='identity_card',
            field=models.CharField(help_text='National identity card number.', max_length=100, verbose_name='Identity Card Number'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the application.', max_length=20, verbose_name='Status'),
        ),
    ]
