# Generated by Django 5.2.3 on 2025-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_privatecourse_paymentsimulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image for the teacher profile (optional).', null=True, upload_to='teacher_profiles/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='city',
            field=models.CharField(blank=True, help_text='City of residence.', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='identity_card',
            field=models.CharField(blank=True, help_text='National identity card number.', max_length=100, null=True, verbose_name='Identity Card Number'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number (optional).', max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
